{{- /* 
  This example shows how to generate a new secret and re-use previously
  generated secrets from the cluster.

  Use lookup to find the existing secret:
  https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function

  Whenever possible, avoid this pattern. It is more secure to generate and
  rotate your credentials during upgrades.
*/}}

{{- $getSecret := (lookup "v1" "Secret" .Release.Namespace "my-secret-name") }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: my-secret-name
data:
  {{- if empty $getSecret }}
  my-key: {{ randAlphaNum 12 | b64enc }}
  {{- else }}
    {{- toYaml $getSecret.data | nindent 2 }}
  {{- end }}