---
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-system

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  namespace: metrics-system
  name: metrics-server
spec:
  interval: 5m
  url: https://kubernetes-sigs.github.io/metrics-server

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: metrics-system
  name: metrics-server
spec:
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      version: ~3.8.0
  dependsOn: []
  interval: 5m
  releaseName: metrics-server
  targetNamespace: metrics-system
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    # this is necessary for some CNI's like calico and cilium
    # hostNetwork:
    #   enabled: true

    # necessary when cluster CA is not setup correctly, typically in dev
    args:
    - --kubelet-insecure-tls
