---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  namespace: cert-manager
  name: jetstack-io
spec:
  interval: 5m
  url: https://charts.jetstack.io

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: cert-manager
  name: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack-io
      version: ~1.10.0
  dependsOn: []
  interval: 5m
  releaseName: cert-manager
  targetNamespace: cert-manager
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
