---
apiVersion: v1
kind: Namespace
metadata:
  name: dex

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  namespace: dex
  name: dexipd
spec:
  interval: 5m
  url: https://charts.dexidp.io

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: dex
  name: dex
spec:
  chart:
    spec:
      chart: dex
      sourceRef:
        kind: HelmRepository
        name: dexipd
      version: ~0.12.1
  dependsOn: []
  interval: 5m
  releaseName: dex
  targetNamespace: dex
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
