---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  namespace: external-dns
  name: external-dns
spec:
  interval: 5m
  url: https://kubernetes-sigs.github.io/external-dns

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: external-dns
  name: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
      version: ~1.12.0
  dependsOn: []
  interval: 5m
  releaseName: external-dns
  targetNamespace: external-dns
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
