---
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-system

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  namespace: metrics-system
  name: grafana
spec:
  interval: 5m
  url: https://grafana.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: metrics-system
  name: loki
spec:
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: ~2.8.8
  dependsOn: []
  interval: 5m
  releaseName: loki
  targetNamespace: metrics-system
  upgrade:
    remediation:
      remediateLastFailure: true
  values: {}

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: metrics-system
  name: grafana
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: ~6.48.0
  dependsOn: []
  interval: 5m
  releaseName: grafana
  targetNamespace: metrics-system
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    datasources: null
    datasources.yaml:
      apiVersion: 1
      datasources:
        - access: proxy
          isDefault: true
          name: Metrics (Prometheus)
          type: prometheus
          url: http://prometheus-server
        - access: proxy
          isDefault: false
          jsonData: {}
          name: Logs (Loki)
          type: loki
          uid: ""
          url: http://loki:3100
          version: 1
    sidecar:
      datasources:
        enabled: true
        label: grafana_datasource
        labelValue: "true"
        maxLines: 1000
