---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  namespace: ingress-nginx
  name: ingress-nginx
spec:
  interval: 5m
  url: https://kubernetes.github.io/ingress-nginx

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: ingress-nginx
  name: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: ~4.4.0
  dependsOn: []
  interval: 5m
  releaseName: ingress-nginx
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    controller:
      ingressClassResource:
        default: true
        enabled: true
      prometheus:
        enabled: true
      replicaCount: 2
      service:
        enabled: true
        type: LoadBalancer
