---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  namespace: metrics-system
  name: keda
spec:
  interval: 5m
  url: https://kedacore.github.io/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: metrics-system
  name: keda
spec:
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: keda
      version: ~2.9.0
  dependsOn: []
  interval: 5m
  releaseName: keda
  targetNamespace: metrics-system
  upgrade:
    remediation:
      remediateLastFailure: true
  values: {}
