---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-operator

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  namespace: minio-operator
  name: minio
spec:
  interval: 5m
  url: https://operator.min.io

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: minio-operator
  name: operator
spec:
  chart:
    spec:
      chart: operator
      sourceRef:
        kind: HelmRepository
        name: minio
      ## Find the latest version with this command
      ## curl -s https://operator.min.io/index.yaml | yq '.entries.operator[0]'
      version: 4.5.8
  dependsOn: []
  interval: 5m
  releaseName: operator
  targetNamespace: minio-operator
  upgrade:
    remediation:
      remediateLastFailure: true
