---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  namespace: flux-system
  name: weaveworks
spec:
  type: "oci"
  interval: 5m
  url: oci://ghcr.io/weaveworks/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: flux-system
  name: weave-gitops
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weaveworks
      version: ~4.0.12
  dependsOn: []
  interval: 5m
  timeout: 90s
  releaseName: weave-gitops
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    ## Reference Values:
    ##   helm show values oci://ghcr.io/weaveworks/charts/weave-gitops

    ## Should the 'oidc-auth' secret be created. For a detailed
    ## explanation of these attributes please see our documentation:
    ## https://docs.gitops.weave.works/docs/configuration/securing-access-to-the-dashboard/#login-via-an-oidc-provider
    oidcSecret:
      create: false
      # clientID:
      # clientSecret:
      # issuerURL:
      # redirectURL:


    ## Create an admin user
    adminUser:
      create: false
      # username: admin

      ## Generate a random password.
      ##   htpasswd -bnBC 10 "" $(openssl rand -hex 30 | tee /dev/stderr) | cut -c2- | tr -d '\n' | pbcopy
      ##
      ## Choose your own password.
      ##   htpasswd -nBC 10 "" | cut -c2- |  tr -d '\n' | pbcopy
      ##
      ## The password set here is: admin
      # passwordHash: $2y$10$b7PDB.B7P2uQpsKvlMys1e/DMXJ6Mc/cd8j4uh1Th8EOeccPxpwX.


    rbac:
      ## Ensure admin user can impersonate resources
      # impersonationResourceNames: [ "admin" ]
