---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stematiclabs:dex-user-group
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stematiclabs:dex-user
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: stematiclabs:dex-user

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stematiclabs:dex-user
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - buckets
  - helmcharts
  - gitrepositories
  - helmrepositories
  - ocirepositories
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - notification.toolkit.fluxcd.io
  resources:
  - providers
  - alerts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.contrib.fluxcd.io
  resources:
  - terraforms
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
- apiGroups:
  - notification.toolkit.fluxcd.io
  resources:
  - providers
  - alerts
  verbs:
  - get
  - list
  - watch
  - patch

