---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lvm-myvolumegroup
allowVolumeExpansion: true
parameters:
  storage: lvm
  volgroup: myvolumegroup
provisioner: local.csi.openebs.io
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values:
    - kind-worker
    - kind-worker2
    - kind-worker3
volumeBindingMode: WaitForFirstConsumer
